# NW/UserBundle/Resources/config/validation.yml

NW\UserBundle\Entity\Novias:
    properties:
        nombre:
            - NotBlank: ~
        #sNombre:
        aPaterno:
            - NotBlank: ~
        aMaterno:
            - NotBlank: ~
        eMail:
            - NotBlank: ~
            - Email:
                checkMX: true
        lada:
            - NotBlank: ~
        telefono:
            - NotBlank: ~
        celular:
            - NotBlank: ~
        direccion:
            - NotBlank: ~
        estado:
            - NotBlank: ~
        ciudad:
            - NotBlank: ~
        cp:
            - NotBlank: ~

NW\UserBundle\Entity\Novios:
    properties:
        nombre:
            - NotBlank: ~
        #sNombre:
        aPaterno:
            - NotBlank: ~
        aMaterno:
            - NotBlank: ~
        eMail:
            - NotBlank: ~
            - Email:
                checkMX: true
        lada:
            - NotBlank: ~
        telefono:
            - NotBlank: ~
        celular:
            - NotBlank: ~
        direccion:
            - NotBlank: ~
        estado:
            - NotBlank: ~
        ciudad:
            - NotBlank: ~
        cp:
            - NotBlank: ~

NW\UserBundle\Entity\Reportero:
    properties:
        nombreRazon:
            - NotBlank: ~
        apellidoPaterno:
            - NotBlank: ~
        apellidoMaterno:
            - NotBlank: ~
        rfc:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email:
                checkMX: true
        lada:
            - NotBlank: ~
        telefono:
            - NotBlank: ~
        celular:
            - NotBlank: ~
        direccion:
            - NotBlank: ~
        ciudad:
            - NotBlank: ~
        cp:
            - NotBlank: ~

NW\UserBundle\Entity\registroproveedores:
    properties:
        tipoPersona:
            - NotBlank: ~
        nombreRazon:
            - NotBlank: ~
        apellidoPaterno:
            - NotBlank: ~
        apellidoMaterno:
            - NotBlank: ~
        rfc:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email:
                checkMX: true
        lada:
            - NotBlank: ~
        telefono:
            - NotBlank: ~
        celular:
            - NotBlank: ~
        direccion:
            - NotBlank: ~
        estado:
            - NotBlank: ~
        ciudad:
            - NotBlank: ~
        cp:
            - NotBlank: ~