root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /es
        permanent: true

pg_pary_root:
    path:     /
    defaults: { _controller: PGPartyBundle:Default:index }

pg_party_homepage:
    path:     /{_locale}/
    defaults: { _controller: PGPartyBundle:Default:index }
    requirements:
        _locale: en|es

pg_party_party:
    path:     /{_locale}/bucketgift
    defaults: { _controller: PGPartyBundle:Default:party }
    requirements:
        _locale: en|es

pg_party_miCuenta:
    path:     /{_locale}/micuenta
    defaults: { _controller: PGPartyBundle:Account:miCuenta }
    requirements:
        _locale: en|es

pg_party_registro:
    path:     /{_locale}/registro
    defaults: { _controller: PGPartyBundle:Users:registro }
    requirements:
        _locale: en|es

pg_party_checarmicuenta:
    path:     /checarmicuenta
    defaults: { _controller: PGPartyBundle:Users:checarmicuenta }