root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /es
        permanent: true

pg_pary_root:
    path:     /
    defaults: { _controller: PGPartyBundle:Default:index }

pg_party_homepage:
    path:     /{_locale}/
    defaults: { _controller: PGPartyBundle:Default:index }
    requirements:
        _locale: en|es

pg_party_admin_panel:
    pattern:  /admin
    defaults: { _controller: PGPartyBundle:Admin:panel }

pg_party_admin_operaciones:
    pattern:  /admin/operaciones

pg_party_admin_operaciones_aceptar_retiro:
    pattern:  /admin/operaciones/aceptar-retiro/{id}
    defaults: { _controller: PGPartyBundle:Admin:aceptarRetiro }

pg_party_admin_operaciones_denegar_retiro:
    pattern:  /admin/operaciones/denegar-retiro/{id}
    defaults: { _controller: PGPartyBundle:Admin:denegarRetiro }

pg_party_party:
    path:     /{_locale}/partygift/{id}
    defaults: { _controller: PGPartyBundle:Default:party }
    requirements:
        _locale: en|es

pg_party_miCuenta:
    path:     /{_locale}/micuenta
    defaults: { _controller: PGPartyBundle:Account:miCuenta }
    requirements:
        _locale: en|es

pg_party_registro:
    path:     /{_locale}/registro
    defaults: { _controller: PGPartyBundle:Users:registro }
    requirements:
        _locale: en|es

pg_party_checarmicuenta:
    path:     /checarmicuenta
    defaults: { _controller: PGPartyBundle:Users:checarmicuenta }

pg_party_modificarcuenta:
    path:      /modificarcuenta
    defaults:  { _controller: PGPartyBundle:Account:modificarCuenta }

pg_party_bucketgift_delete:
    pattern:  /micuenta/bucketgift/{id}/delete
    defaults: { _controller: PGPartyBundle:Account:bucketGiftDelete }

pg_party_partygift_delete:
    pattern:  /micuenta/partygift/{id}/delete
    defaults: { _controller: PGPartyBundle:Account:partyGiftDelete }

pg_party_busqueda:
    path:     /{_locale}/busqueda
    defaults: { _controller: PGPartyBundle:Default:busqueda }
    requirements:
        _locale: en|es

pg_party_changepass:
    pattern:  /{_locale}/changepass/{id}
    defaults: { _controller: PGPartyBundle:Users:changePass, id: false }
    requirements:
        _locale: en|es

pg_party_pruebas:
    pattern:  /pruebas
    defaults: { _controller: PGPartyBundle:Default:pruebas }

pg_party_pruebas_regalos_operaciones:
    pattern:  /regalos-regalados

pg_party_pruebas_regalos_operaciones_descargar:
    pattern:  /regalos-regalados/descargar/{id}
    defaults: { _controller: PGPartyBundle:Default:descargarRegalos }

pg_party_pruebas_regalos_generar_pdf:
    pattern:  /pdf/regalos/generar-pdf/{id}
    defaults: { _controller: PGPartyBundle:Default:generarPdfRegalos }